apiVersion: v1
kind: Service
metadata:
  labels:
    tier: ui
  name: todo-react-app
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 30004
  selector:
    tier: ui
  type: NodePort